#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex evo_art.tex && latex evo_art.tex &&  latex evo_art.tex && bibtex evo_art && latex evo_art.tex && latex evo_art.tex && latex evo_art.tex && echo "-----------------------------" && dvips evo_art.dvi -o && ps2pdf evo_art.ps && echo " "
